<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CorrectnessTest" tests="2" skipped="0" failures="2" errors="0" timestamp="2019-12-24T21:19:53" hostname="akifev" time="6.02">
  <properties/>
  <testcase name="testSpuriousWakeup" classname="CorrectnessTest" time="3.012">
    <failure message="org.junit.runners.model.TestTimedOutException: test timed out after 3000 milliseconds" type="org.junit.runners.model.TestTimedOutException">org.junit.runners.model.TestTimedOutException: test timed out after 3000 milliseconds
	at java.base@11.0.4/java.lang.Object.wait(Native Method)
	at java.base@11.0.4/java.lang.Object.wait(Object.java:328)
	at app//CorrectnessTest$Runner.awaitPhase(CorrectnessTest.kt:93)
	at app//CorrectnessTest$Runner.awaitCritical(CorrectnessTest.kt:86)
	at app//CorrectnessTest.testSpuriousWakeup(CorrectnessTest.kt:53)
	at java.base@11.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.4/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.4/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base@11.0.4/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.4/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <testcase name="testFCFS" classname="CorrectnessTest" time="3.008">
    <failure message="org.junit.runners.model.TestTimedOutException: test timed out after 3000 milliseconds" type="org.junit.runners.model.TestTimedOutException">org.junit.runners.model.TestTimedOutException: test timed out after 3000 milliseconds
	at java.base@11.0.4/java.lang.Object.wait(Native Method)
	at java.base@11.0.4/java.lang.Object.wait(Object.java:328)
	at app//CorrectnessTest$Runner.awaitPhase(CorrectnessTest.kt:93)
	at app//CorrectnessTest$Runner.awaitCritical(CorrectnessTest.kt:86)
	at app//CorrectnessTest.testFCFS(CorrectnessTest.kt:16)
	at java.base@11.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.4/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.4/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.4/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base@11.0.4/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.4/java.lang.Thread.run(Thread.java:834)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
